import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Chat app",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <section>
                    <h1>Header</h1>
                    {children}
                    <h1>Footer</h1>
                </section>
            </body>
        </html>
    );
}
